name: scribbly
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.0.8
  http: ^0.13.5
  url_launcher: ^6.1.5
  settings_ui: ^2.0.2
  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
    - family: PT Sans
      fonts:
        - asset: fonts/PTSans/PTSans-Regular.ttf
        - asset: fonts/PTSans/PTSans-Italic.ttf
          style: italic
        - asset: fonts/PTSans/PTSans-Bold.ttf
          weight: 700
        - asset: fonts/PTSans/PTSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto Slab
      fonts:
        - asset: fonts/RobotoSlab/RobotoSlab-Regular.ttf
        - asset: fonts/RobotoSlab/RobotoSlab-Light.ttf
          weight: 300
        - asset: fonts/RobotoSlab/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/RobotoSlab/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
    - family: Lexend
      fonts:
        - asset: fonts/Lexend/Lexend-Regular.ttf
        - asset: fonts/Lexend/Lexend-Bold.ttf
          weight: 700
